### ISSUE TITLE
Removing old backups

### ISSUE THREAD

**Issue by SerhiiZahuba** [DanSheps/netbox-config-backup#29]
### Plugin version

1.2.4

### NetBox version

3.2

### Feature type

New functionality

### Proposed functionality

It is necessary to add to the config the ability to specify how many days and / or the number of backups to store them. That is, there should be two parameters
1) Delete backups older than .... days
2) Delete backups older, for example 20, i.e. 21 backup, no matter for what period it will be deleted.

### Use case

no need to manually delete old backups

**Comment by DanSheps** [comment]
Due to the nature of Git, you cannot remove backups.
