### ISSUE TITLE
Backup logging

### ISSUE THREAD

**Issue by SerhiiZahuba** [DanSheps/netbox-config-backup#30]
### Plugin version

1.2.4

### NetBox version

3.2

### Feature type

New functionality

### Proposed functionality

I suggest adding backup logging. That is, adding a log file on the server where information about how the backup was made will be written. With different log levels (Warning, Debug, Info, etc.)

### Use case

This will help a lot in debugging problems. For example, with 200 devices it will be very difficult to debug only on the basis of the web.

**Comment by DanSheps** [comment]
There is already some logging in place, you just need to enable the logging.
