### ISSUE TITLE
adding pagination to the backup page

### ISSUE THREAD

**Issue by SerhiiZahuba** [DanSheps/netbox-config-backup#41]
### Plugin version

1.2.4

### NetBox version

3.2

### Feature type

New functionality

### Proposed functionality

I suggest adding pagination to the backup page. Very inconvenient when there are 20-40 backups, the page will be very large.
![image](https://user-images.githubusercontent.com/36307887/166104720-282e7611-a9c6-459f-b237-3998975234ed.png)

### Use case

This will add convenience to navigation between backups.

**Comment by DanSheps** [comment]
Completed in #55
