### ISSUE TITLE
Incorrect link (when deleting a device)

### ISSUE THREAD

**Issue by SerhiiZahuba** [DanSheps/netbox-config-backup#42]
### Plugin version

1.2.4

### NetBox version

3.2

### Python version

3.9

### Steps to Reproduce

If you go to the backup task and click delete on top, then after deletion, the transition goes to the main page of the site. It would be logical that after deleting the task, the redirect would be to the main page of the module.

### Expected Behavior

I expect to get to the main page of the module.

### Observed Behavior

Go to main page.

**Comment by DanSheps** [comment]
This needs to be fixed in the upstream
