### ISSUE TITLE
NetBox version 3.3.5 not supported

### ISSUE THREAD

**Issue by alexanderdeca** [DanSheps/netbox-config-backup#47]
### Plugin version

v1.2.7

### NetBox version

v3.3.5

### Python version

3.8

### Steps to Reproduce

1. Install Plugin
2. Configure netbox plugin
3. Run the migrate common 

### Expected Behavior

Successful install.

### Observed Behavior

File "/opt/netbox-3.3.5/netbox/netbox/settings.py", line 677, in <module>
    plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)
  File "/opt/netbox-3.3.5/netbox/extras/plugins/__init__.py", line 101, in validate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Plugin netbox_config_backup requires NetBox maximum version 3.2.99.

**Comment by DanSheps** [comment]
Should be releasing a new version shortly, sorry about this.
