### ISSUE TITLE
Backup stops working on some devices

### ISSUE THREAD

**Issue by Uzilurcs** [DanSheps/netbox-config-backup#52]
### Plugin version

v1.2.8

### NetBox version

v3.3.9

### Python version

3.8

### Steps to Reproduce

1. Create backup - backup runs instand.
2. after a day backup stops  - we see on "Last Backup" just " -- " and on backupcount " 2 "
3. We see in the Logs:
Exception at line 148 on job: HOSTNAME
Exception at line 148 on job: HOSTNAME
Exception at line 148 on job: HOSTNAME
Exception at line 148 on job: HOSTNAME

### Expected Behavior

Backup should work

### Observed Behavior

Backup not work

**Comment by DanSheps** [comment]
Yes, it normally happens when there is an exception.  I think I have captured all the cases where this happens to requeue the backup job at least.

**Comment by Uzilurcs** [comment]
Hey Dan,
the job is requeued but not running. The exception erverytime shows up

**Comment by DanSheps** [comment]
What is the exception?

**Comment by Uzilurcs** [comment]
hmm sorry. i have only Exception at line 148 on job: HOSTNAME...

**Comment by DanSheps** [comment]
This should be mostly fixed in #55
