### ISSUE TITLE
Page not fount at Configuration tab

### ISSUE THREAD

**Issue by joaolucasmacedo** [DanSheps/netbox-config-backup#59]
### Plugin version

v1.4.1

### NetBox version

v3.4.6

### Python version

3.9

### Steps to Reproduce

1. Click on configuration tab at a given device backup.

### Expected Behavior

Chow configuration

### Observed Behavior

Page not found.

I'm using Python 3.10.6.
I don't know if I'm missing something but I've followed the instructions and my devices also have NAPALM access. The plugin has created 2 running config files on the git repo, but I can't see anything on Netbox UI.

**Comment by towdie** [comment]
Hello, we have same issue here.
Napalm is working as I can see downloaded config in device tab, and also some status and other things.

On Configuration Backup plugin, if I will create new backup job for device i can see schedulled task, I see last run of the job and last success, but last change is showing just dash even if we have some change in the config.
Also the backup count is showing "No backup commit tree changes found" and count is 0.

If I click on Configuration tab I am getting "Page Not Found"
/plugins/configbackup/devices/5/config/
The requested page does not exist.

Version of netbox: 3.6.1
Version of the Configuration Backup plugin: 1.5.0
Version of Napalm plugin: 0.1.6
Version of Python: 3.2.0

Am I missing some configuration or some step?

**Comment by towdie** [comment]
Hello, for the test I created also another VM with Netbox(now I have on in docker and one standalone on Ubuntu) and on both it is acting same. I also tested different devices(Cisco, Juniper) and on both backup count is 0 even if I will do some changes in configurations. Also the tabs For config and diff are showing page not found.

**Comment by DanSheps** [comment]
If there are no backups, then it will result in a page not found error.

**Comment by DanSheps** [comment]
> I don't know if I'm missing something but I've followed the instructions and my devices also have NAPALM access. The plugin has created 2 running config files on the git repo, but I can't see anything on Netbox UI.

Could you open a command line and try:

python3 manage.py rebuild
