### ISSUE TITLE
mikrotik support

### ISSUE THREAD

**Issue by SerhiiZahuba** [DanSheps/netbox-config-backup#65]
### Plugin version

1.4.3

### NetBox version

3.5.1

### Feature type

New functionality

### Proposed functionality

Please check the possibility to add Mikrotik backup.

### Use case

Please check the possibility to add Mikrotik backup. As I pointed out in https://github.com/DanSheps/netbox-config-backup/discussions/40 the napalm-ros module already has support for getting the device config

print(device.get_config())

![image](https://github.com/DanSheps/netbox-config-backup/assets/36307887/21d85bcc-461c-4ba6-b106-fa13afea3717)
![image](https://github.com/DanSheps/netbox-config-backup/assets/36307887/93bd8c93-c8f9-435d-8be5-40b8ec2032dc)

import napalm
from napalm_ros import ros
router_ip = '***'
router_port = 8728
router_user = 'admin'
router_pass = '***'
driver = napalm.get_network_driver('ros')
print('Connecting to', router_ip, "on port", router_port, "as", router_user)
device = driver(hostname=router_ip, username=router_user, password=router_pass, optional_args={'port': router_port})
device.open()
print(device.get_config())

**Comment by DanSheps** [comment]
This should just be a configuration on the end user side, I don't believe there is anything in the plugin that prevents you from choosing ros for the driver.
