### ISSUE TITLE
Could not resolve URL for hyperlinked relationship using view name "plugins-api:netbox_sync-api:sync-detail"

### ISSUE THREAD

**Issue by exec-to** [DanSheps/netbox-config-backup#69]
### Plugin version

1.4.5

### NetBox version

3.5.3

### Python version

3.9

### Steps to Reproduce

1. In Netbox open edit backup job view and press "Save" button or delete backup job.

### Expected Behavior

The backup job must be updated or deleted.

### Observed Behavior

An exception is thrown:

```
<class 'django.core.exceptions.ImproperlyConfigured'>

Could not resolve URL for hyperlinked relationship using view name "plugins-api:netbox_sync-api:sync-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.

Python version: 3.10.7
NetBox version: 3.5.3
```

**Comment by HTLBraunau** [comment]
+1 
I have installed the plugin today and got the exact same issue. i´d love to have a solution, i really want to try that plugin.

**Comment by DanSheps** [comment]
Looks like it might be pulling in from an internal plugin.

I will take a look and push out an update later today.

**Comment by HTLBraunau** [comment]
Hi!
Thank you for the quick fix. I could need some help for updating the plugin, i´m kind of a noob here. I tried to update via pip install --upgrade but it did not change a thing. Could someone maybe point me in the right direction? 
Thanks!

**Comment by exec-to** [comment]
> Hi! Thank you for the quick fix. I could need some help for updating the plugin, i´m kind of a noob here. I tried to update via pip install --upgrade but it did not change a thing. Could someone maybe point me in the right direction? Thanks!

Hi @HTLBraunau !

Do you activate netbox virtualenv before upgrade plugin?
```
# source /opt/netbox/venv/bin/activate
```

Also you can check installed version of the plugin in virtualenv:
```
# pip show netbox-config-backup
```

Try upgrade the plugin with this command:
```
/opt/netbox/venv/bin/pip install -U netbox-config-backup
```

**Comment by HTLBraunau** [comment]
Yes i did enable the venv! But i didn´t quite get the pip command right. with the flag -U it did work flawlessly. Thank you very much @exec-to!
