### ISSUE TITLE
Configuration and Diff  page not found

### ISSUE THREAD

**Issue by wanghuan12345678** [DanSheps/netbox-config-backup#81]
### Plugin version

v1.5.0

### NetBox version

v 3.6.4

### Python version

3.9

### Steps to Reproduce

/plugins/configbackup/devices/16/config/
The requested page does not exist.
![image](https://github.com/DanSheps/netbox-config-backup/assets/69284187/c493fd1f-180b-448d-befe-8eff60d0de29)

![image](https://github.com/DanSheps/netbox-config-backup/assets/69284187/4a040d71-9089-4ffa-87f0-ec5e7314d982)

![image](https://github.com/DanSheps/netbox-config-backup/assets/69284187/e6da2a6a-9061-4e42-9565-2e9d62be2020)

### Expected Behavior

i hope  this page is ok

### Observed Behavior

The requested page does not exist.

**Comment by DanSheps** [comment]
This is the result of no commits being found and is intended.
