### ISSUE TITLE
configbackup/devices/add/ -- Not populating Devices and IP part of the Netbox

### ISSUE THREAD

**Issue by techtronix-868** [DanSheps/netbox-config-backup#91]
### Plugin version

v1.5.4

### NetBox version

v3.7.5

### Python version

3.8

### Steps to Reproduce

1. Python Version:-- 3.11
2. Postgres Version:-- 16
3. Redis:-- 5.0.3 
4. Connect Plugin to NetBox Following Steps in Readme
5. On clicking 'add' unable to find device and ip address. The filters and search bars are empty. The DCIM has two demo devices

### Expected Behavior

Expected to see the two devices

### Observed Behavior

No results for devices.
![image](https://github.com/DanSheps/netbox-config-backup/assets/52819188/655288da-ba06-44eb-a6fc-87a1614dd980)

**Comment by DanSheps** [comment]
You need to have netbox-napalm installed and activated with the device also having a napalm setting.
